server:
  service:
    type: LoadBalancer
  nodeSelector:
    workload: argocd
  tolerations:
    - key: workload
      operator: Equal
      value: argocd
      effect: NoSchedule

repoServer:
  nodeSelector:
    workload: argocd
  tolerations:
    - key: workload
      operator: Equal
      value: argocd
      effect: NoSchedule

applicationSet:
  nodeSelector:
    workload: argocd
  tolerations:
    - key: workload
      operator: Equal
      value: argocd
      effect: NoSchedule

controller:
  nodeSelector:
    workload: argocd
  tolerations:
    - key: workload
      operator: Equal
      value: argocd
      effect: NoSchedule

redis:
  nodeSelector:
    workload: argocd
  tolerations:
    - key: workload
      operator: Equal
      value: argocd
      effect: NoSchedule
