server:
  service:
    type: LoadBalancer
  nodeSelector:
    workload: argocd
  tolerations:
    - key: workload
      operator: Equal
      value: argocd
      effect: NoSchedule

repoServer:
  nodeSelector:
    workload: argocd
  tolerations:
    - key: workload
      operator: Equal
      value: argocd
      effect: NoSchedule

applicationSet:
  nodeSelector:
    workload: argocd
  tolerations:
    - key: workload
      operator: Equal
      value: argocd
      effect: NoSchedule

controller:
  nodeSelector:
    workload: argocd
  tolerations:
    - key: workload
      operator: Equal
      value: argocd
      effect: NoSchedule

redis:
  nodeSelector:
    workload: argocd
  tolerations:
    - key: workload
      operator: Equal
      value: argocd
      effect: NoSchedule

configs:
  secret:
    argocdInitialAdminSecret: "$$2y$10$VttJmtPYjd8vfDXfP8pZ2.2NcZw7NhE2qnKD0TuAws.Yw1rEADPLy"  # password: admin
